# Generated by Django 4.2.4 on 2023-09-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBasic',
            fields=[
                ('UID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
    ]
