# Generated by Django 4.2.4 on 2023-09-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasic',
            name='likes',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='userbasic',
            name='style',
            field=models.IntegerField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbasic',
            name='username',
            field=models.CharField(default='fakeuser', max_length=255),
            preserve_default=False,
        ),
    ]
