# Generated by Django 4.2.4 on 2023-10-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userbasic_likes_userbasic_style_userbasic_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasic',
            name='style',
            field=models.CharField(default='extreme', max_length=20),
        ),
    ]
