# Generated by Django 4.2.4 on 2023-12-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userbasic_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionName', models.CharField(max_length=255)),
                ('weight', models.IntegerField(default=0, max_length=4)),
                ('reps', models.IntegerField(default=0, max_length=2)),
                ('UID', models.IntegerField()),
                ('timeAdd', models.TimeField()),
            ],
        ),
    ]
